Re-enable http/2
ipfs/bifrost-gateway pull request #95
Opened 2023-04-13 21:05 UTC by willscott

By setting a custom TLSClientConfig we remove the default of having a `NextProtos` set and need to add it back

2023-04-13 22:18 UTC, lidel requested changes
Thanks! I suspect it is not that easy:

```
failed to resolve /ipfs/bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi: Bad Gateway: http request failed: Get "https://38.93.247.224/ipfs/bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi?format=raw": http2: no cached connection was available
```

Unless you get to this first, I can look into this after IPFS Thing.


Quick thoughts:
- good opportunity to clean up and move generic client things to `http_client.go` so HTTP2-enabled client can be  reused by  `blockstore_proxy.go` and `routing.go`
  - caveat: non-HTTPS endpoints like `PROXY_GATEWAY_URL=http://127.0.0.1:8080` need to work.   
     - Maybe `http2.Transport{AllowHTTP: true`  will do the trick?

2023-04-14 00:23 UTC, DiegoRBaquero approved these changes

2023-04-14 06:08 UTC, willscott commented
explanation potentially around context of the 'no cached connection available' at https://github.com/golang/go/issues/16582

2023-04-15 12:04 UTC, willscott commented
@lidel  - i think we want a`http2.Transport` at the basis instead of a an `http.Transport`. That means a custom `DialTLSContext` method to make use of the cached DNS dialer, unfortunately.
See if this basic structure seems plausible.

2023-04-18 14:33 UTC, willscott commented
It looks like we could potentially just set `ForceAttemptHTTP2` on the standard http transport. I'll try simplifying to that
https://go.googlesource.com/go/+/master/src/net/http/transport.go#288

2023-04-18 14:37 UTC, closed without merging